### Auth
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{ "email":"flyingcat@example.com", "username":"flying_cat", "password":"rainbow" }

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{ "email":"flyingcat@example.com", "password":"rainbow" }

### Me
GET http://localhost:8080/api/users/me

### Create Schedule
POST http://localhost:8080/api/schedules
Content-Type: application/json

{ "title":"첫 일정", "content":"내용" }

### List Schedules
GET http://localhost:8080/api/schedules?page=0&size=10
